### PR TITLE
CPO: Increase timeout for e2e conformance tests

### PR DESCRIPTION
**Pull request by ramineni**
Seeing occasional interrupts in conformance jobs resulting in failure.
This PR increases the timeout  and explicitly set the disable-log-dump=false

### CODE REVIEW

**Comment by ramineni** [comment]
cc @lingxiankong

**Review by wangxiyuan — APPROVED** [review]

**Review by wangxiyuan — APPROVED** [review]
ready to move on?

**Comment by ramineni** [comment]
@wangxiyuan yes, please merge

**Comment by ramineni** [comment]
@wangxiyuan could you merge this PR?

**Pull request merged**
