### PR TITLE
Fixes issue #76

### PR DESCRIPTION
**Pull request by mrhillsman**
Change q- enabled services to neutron-

Signed-off-by: Melvin Hillsman <mrhillsman@gmail.com>

### CODE REVIEW

**Comment by hogepodge** [comment]
What about LBaaSv2 or Octavia? These are critical for cloud controller manager testing.

**Comment by dims** [comment]
Approved

**Comment by mrhillsman** [comment]
@hogepodge we have another for octavia that i know of but believe that is waiting for review #72 this one is for something @dims found checking job output

if there is no movement on #72 i can see what is going on with it?

**Comment by dims** [comment]
@hogepodge we are trying to get the basic unit tests running. failing `TestRoutes` unit test in (occm), so trying to see if we can switch away from neutron-legacy to see if helps

**Pull request merged**
