### PR TITLE
Use ruby 2.4.0 instead for manageiq jobs

### PR DESCRIPTION
**Pull request by huangtianhua**
An error occurred while installing dry-validation (0.13.1),
and Bundler cannot continue for manageiq jobs.
Change to use ruby 2.4.0 to fix this bug.

Related-Bug: theopenlab/openlab#246

### CODE REVIEW

**Comment by liu-sheng** [comment]
tested OK in allinone env ?

**Comment by liu-sheng** [comment]
@theopenlab-ci seems this job cannot pass due to test cases failure,  you can check the previous logs to confirm.

**Comment by h00130372** [comment]
@liu-sheng What do you mean the 'test cases failure'? The earliest log I can found  is http://status.openlabtesting.org/build/f3e0feb399aa4a8789aea2019ed7a114, and the build failed is because the libssl-dev package is not found(this fixed in https://github.com/theopenlab/openlab/issues/242)

**Comment by huangtianhua** [comment]
@liu-sheng @Yikun let's merge this first, the manageiq jobs failed and have several problems, this is the first step to continue run the job.

**Comment by huangtianhua** [comment]
@Yikun Thanks. We disabled the jobs of manageiq against with public clouds almost two months ago, so I think we can change it once the jobs enabled again?

**Comment by Yikun** [comment]
@huangtianhua Yes, I think we can.

**Pull request merged**
