### PR TITLE
Set use-octavia to true

### PR DESCRIPTION
**Pull request by mrhillsman**
Signed-off-by: Melvin Hillsman <codebauss@gmail.com>

### CODE REVIEW

**Comment by mrhillsman** [comment]
Approved

**Comment by mrhillsman** [comment]
Addresses issue #162 

We should be using Octavia by default if possible due to issues with LBaaSv2 inconsistencies.

**Comment by mrhillsman** [comment]
@liu-sheng @animationzl @kiwik

**Comment by dims** [comment]
@liu-sheng the builds are already very flaky. how bad can it get with this change :) merging

**Comment by liu-sheng** [comment]
the "use-octavia=True" option make the lbaas resource request passed to the octavia service endpoint, also need to change the resource cleanup(https://github.com/theopenlab/openlab-zuul-jobs/blob/master/playbooks/cloud-provider-openstack-acceptance-test-lb-octavia/post.yaml) to use OSC commands than neutron CLI commands. will make a corresponding PR to change that.

In my own testing, I have also add the "use-octavia=True" option and changed to use OSC commands in cleanup. but problems remains. please see: https://github.com/liu-sheng/cloud-provider-openstack/pull/12  The lbaas job will success  sometimes. but sometimes the loadbalancer created by the job may become in `ERROR` state and even cannot be deleted. seems there are some problems with Vexxhost cloud, it's hard to find the detailed reason since we cannot get the related log of vexxhost services.

Hi @mrhillsman， Ruichen has told me that you will ask the vexxhost operators about the services stability of vexxhost services ? any feadback ?

Thanks!

**Comment by kiwik** [comment]
Related-Bug: https://github.com/theopenlab/openlab/issues/50

**Pull request merged**
