### PR TITLE
[CPO] Remove post run for e2e conformance

### PR DESCRIPTION
**Pull request by ramineni**
This commit removes post run for e2e conformance , as its been removed.

### CODE REVIEW

**Comment by ramineni** [comment]
cc @lingxiankong

**Comment by lingxiankong** [comment]
/lgtm

@ramineni thanks, I totally forgot that.

**Comment by ramineni** [comment]
@wangxiyuan @bzhaoopenstack can we merge this?

**Comment by wangxiyuan** [comment]
@ramineni  sorry, forgot it.

**Pull request merged**
