### PR TITLE
[CPO]Update default etcd server to 3.4.9

### PR DESCRIPTION
**Pull request by ramineni**
Updates default etcd server to 3.4.9, which is default
version of k8s master

### CODE REVIEW

**Comment by ramineni** [comment]
@wangxiyuan pls review

**Comment by seanschneeweiss** [comment]
By setting v3.4.9 as default, it could be considered to remove the overwrites at
* https://github.com/theopenlab/openlab-zuul-jobs/blob/3c06dfcf0e1d3c59949e038dff595f78a546c581/playbooks/cloud-provider-openstack-acceptance-test-csi-cinder/run.yaml#L6
* https://github.com/theopenlab/openlab-zuul-jobs/blob/3c06dfcf0e1d3c59949e038dff595f78a546c581/playbooks/cloud-provider-openstack-e2e-test-csi-cinder/run.yaml#L6
* https://github.com/theopenlab/openlab-zuul-jobs/blob/3c06dfcf0e1d3c59949e038dff595f78a546c581/playbooks/cloud-provider-openstack-acceptance-test-csi-manila/run.yaml#L5

<sub>Sean Schneeweiss <sean.schneeweiss@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>

**Comment by ramineni** [comment]
> By setting v3.4.9 as default, it could be considered to remove the overwrites at
> 
> * https://github.com/theopenlab/openlab-zuul-jobs/blob/3c06dfcf0e1d3c59949e038dff595f78a546c581/playbooks/cloud-provider-openstack-acceptance-test-csi-cinder/run.yaml#L6
> * https://github.com/theopenlab/openlab-zuul-jobs/blob/3c06dfcf0e1d3c59949e038dff595f78a546c581/playbooks/cloud-provider-openstack-e2e-test-csi-cinder/run.yaml#L6
> * https://github.com/theopenlab/openlab-zuul-jobs/blob/3c06dfcf0e1d3c59949e038dff595f78a546c581/playbooks/cloud-provider-openstack-acceptance-test-csi-manila/run.yaml#L5
> 
> Sean Schneeweiss [sean.schneeweiss@daimler.com](mailto:sean.schneeweiss@daimler.com), Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)

@seanschneeweiss Thanks. ya, these could be removed. Let me know if you could do the update.

**Comment by seanschneeweiss** [comment]
@ramineni Sure, update proposed in https://github.com/theopenlab/openlab-zuul-jobs/pull/974.

**Pull request merged**
