### PR TITLE
[TF-OS] Add new playbook for admin user

### PR DESCRIPTION
**Pull request by nikParasyr**
This commit creates a new job for the terraform-openstack-provider.
The job runs with admin credentials allowing to test scenarios that
require admin credentials.

This is a follow-up from https://github.com/theopenlab/openlab/issues/365 and relates to https://github.com/terraform-provider-openstack/terraform-provider-openstack/issues/1211

### CODE REVIEW

**Comment by wangxiyuan** [comment]
you should add a new job defination in `zuul.d/jobs.yaml` as well

**Comment by nikParasyr** [comment]
@wangxiyuan Added it

**Review by wangxiyuan — DISMISSED** [review]
LGTM， once this is merged, don't forget to add the job `terraform-provider-openstack-acceptance-test-admin` into `.zuul.yaml` in your project.

and this change need an openlab restart. I'll let you know once it works.

**Comment by nikParasyr** [comment]
@wangxiyuan Will do but there are some extra changes that are required on the provider. Thanks a lot for your help :)

**Comment by nikParasyr** [comment]
I can just remove the job definition, since there it's probably not in use. i'll doublecheck gopherclouds zuul config just in case

**Comment by nikParasyr** [comment]
It's not defined in any playbook [here](https://github.com/gophercloud/gophercloud/tree/master/.zuul/playbooks)
but there is a newton job defined [here](https://github.com/gophercloud/gophercloud/blob/master/.zuul.yaml)

**Comment by nikParasyr** [comment]
@wangxiyuan Should i remove the jobs that are not defined on gophercloud? I could do it but im not per-se a gophercloud person...

**Comment by wangxiyuan** [comment]
> @wangxiyuan Should i remove the jobs that are not defined on gophercloud? I could do it but im not per-se a gophercloud person...

I just disabled gophercloud in openlab since I assume it has removed openlab github app already.

**Review by wangxiyuan — APPROVED** [review]

**Pull request merged**
