### PR TITLE
[CPO] Enable CSI Snapshotter in e2e tests

### PR DESCRIPTION
**Pull request by ramineni**
Install CSI snapshotter in e2e tests , required to enable snapshot tests

### CODE REVIEW

**Comment by ramineni** [comment]
@wangxiyuan openlab check failed? Is this known issue?

**Comment by wangxiyuan** [comment]
recheck

**Comment by wangxiyuan** [comment]
Just back to work.

It looks that the issue is related to zuul package. Will fix it later.

**Pull request merged**
