### PR TITLE
Move secret and vars to child job

### PR DESCRIPTION
**Pull request by wangxiyuan**
Move secret and vars specify jobs to the definition more clear.

### CODE REVIEW

**Comment by liusheng** [comment]
I think the previours code is implemented in purpose, to extract common part of jobs to parent job, why do this change ?

**Comment by wangxiyuan** [comment]
> I think the previours code is implemented in purpose, to extract common part of jobs to parent job, why do this change ?

see: https://github.com/theopenlab/openlab-zuul-jobs/pull/595#discussion_r307610770

move some vars to child can make the job defination more clear.

**Comment by liusheng** [comment]
> > I think the previours code is implemented in purpose, to extract common part of jobs to parent job, why do this change ?
> 
> see: [#595 (comment)](https://github.com/theopenlab/openlab-zuul-jobs/pull/595#discussion_r307610770)
> 
> move some vars to child can make the job defination more clear.

I think extracting common vars and definitions is what the design purpose, and I don't think currently is not clear to read, when we want to know the vars of a job, we surely search both child and parent jobs.

**Comment by wangxiyuan** [comment]
> > > I think the previours code is implemented in purpose, to extract common part of jobs to parent job, why do this change ?
> > 
> > 
> > see: [#595 (comment)](https://github.com/theopenlab/openlab-zuul-jobs/pull/595#discussion_r307610770)
> > move some vars to child can make the job defination more clear.
> 
> I think extracting common vars and definitions is what the design purpose, and I don't think currently is not clear to read, when we want to know the vars of a job, we surely search both child and parent jobs.

This patch fixed the cpo lb job error  as well: https://logs.openlabtesting.org/logs/23/723/e0a7fceafa166609ecf8d847d8694f467d16acf9/cloud-provider-openstack-acceptance-test-lb-octavia/cloud-provider-openstack-acceptance-test-lb-octavia/cc854c8/job-output.txt.gz

**Comment by wangxiyuan** [comment]
see: https://github.com/theopenlab/openlab-zuul-jobs/pull/619

**Pull request closed without merging**
