### PR TITLE
[CPO] add multi-arch images support

### PR DESCRIPTION
**Pull request by ricolin**
This proposes to build and upload all images for amd64, arm, arm64, ppc64le,
and s390x CPU architectures.

relate to https://github.com/kubernetes/cloud-provider-openstack/issues/883

### CODE REVIEW

**Comment by ricolin** [comment]
Here are some tests against CI environment: https://github.com/kubernetes/cloud-provider-openstack/pull/989

**Comment by ramineni** [comment]
Lets hold this for sometime @wangxiyuan

**Comment by wangxiyuan** [comment]
@ramineni  sure

**Review by huangtianhua — APPROVED** [review]

**Comment by wangxiyuan** [comment]
fell free to reopen if it's still needed.

**Pull request closed without merging**
