### PR TITLE
CPO: Update e2e conformance tests to new releases

### PR DESCRIPTION
**Pull request by ramineni**
This PR is to update conformance job to run against latest branches

### CODE REVIEW

**Comment by ramineni** [comment]
cc @lingxiankong

**Comment by lingxiankong** [comment]
/lgtm

Thanks!

**Review by wangxiyuan — APPROVED** [review]

**Comment by wangxiyuan** [comment]
This need a Zuul restart. I'll let you know once it's done.

**Comment by ramineni** [comment]
@wangxiyuan Thanks. pls let me know once done.

**Comment by wangxiyuan** [comment]
zuul was restarted in last Friday

**Pull request merged**
