### PR TITLE
Disabled cloud-provider-openstack CSIMigration job

### PR DESCRIPTION
**Pull request by chrigl**
I currently don't know what happens there. The job always ends in a
timeout of "kubeadm join". So disabling for now.

### CODE REVIEW

**Comment by chrigl** [comment]
@wangxiyuan Do you maybe have an idea why the bootstrap gets stuck? Are there any security groups in my way?

```
2019-11-13 07:08:31.267492 | k8s-node-1 | + kubeadm join 192.168.0.3:6443 --token t16f2s.xxx --discovery-token-ca-cert-hash sha256:xxx --node-name k8s-node-1
2019-11-13 07:08:31.314602 | k8s-node-1 | [preflight] Running pre-flight checks
2019-11-13 07:08:31.466915 | k8s-node-1 | 	[WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/
2019-11-13 07:08:31.580449 | k8s-node-1 | 	[WARNING Hostname]: hostname "k8s-node-1" could not be reached
2019-11-13 07:08:31.580671 | k8s-node-1 | 	[WARNING Hostname]: hostname "k8s-node-1": lookup k8s-node-1 on 127.0.0.1:53: no such host
2019-11-13 10:04:47.618519 | PRE-RUN END RESULT_TIMED_OUT: [trusted : github.com/theopenlab/openlab-zuul-jobs/playbooks/cloud-provider-openstack-multinode-csi-migration-test/pre.yaml@master]
```

**Comment by wangxiyuan** [comment]
never mind.  Just leave as it is. We can debug and fix it next. I'll try to take a deep look today. Close this PR now.

**Comment by chrigl** [comment]
Hey @wangxiyuan, did you find the time to look at this?
The infinite hanging likely relates to https://github.com/kubernetes/kubeadm/issues/1851. So I would guess there are securitygroups and/or firewalls

Thanks :)

**Comment by wangxiyuan** [comment]
@chrigl  Thanks for the remind. I'll take a look

**Comment by wangxiyuan** [comment]
@chrigl sorry for the late response. It's a security group problem. Fixed now.

**Pull request closed without merging**
