### PR TITLE
CAPO: increase worker count

### PR DESCRIPTION
**Pull request by sbueringer**

### CODE REVIEW

**Comment by sbueringer** [comment]
@wangxiyuan can you approve/merge please? Thx :)

**Comment by sbueringer** [comment]
@wangxiyuan *Push*

**Comment by wangxiyuan** [comment]
Sorry forget it  you can ping me in slack next time to ensue  I can get the message

**Comment by sbueringer** [comment]
> Sorry forget it  you can ping me in slack next time to ensue  I can get the message

Okay thx, no problem 😃

**Pull request merged**
