### PR TITLE
Add missing golang configuration for format job

### PR DESCRIPTION
**Pull request by liu-sheng**

### CODE REVIEW

**Comment by mrhillsman** [comment]
Approved

**Comment by mrhillsman** [comment]
@animationzl if we are using this role ( move-k8s-repo-to-k8s-specific-dir ) we need to also have install-k8s role above it unless I am missing something

**Comment by mrhillsman** [comment]
@liu-sheng please see comment

**Comment by liu-sheng** [comment]
@mrhillsman yes, sure, the move-* role is for change the path from `github/kubernetes/kubernetes` to `k8s.io/kubernetes`, the install-k8s role is for building k8s and starting up.

**Comment by liu-sheng** [comment]
@mrhillsman is this format job need k8s binaries  ? now I only found it missing the `gofmt`

**Comment by liu-sheng** [comment]
@mrhillsman yes I remember there is an issue occurred about the `k8s.io/kubernetes` path when we missed the move-* role, so it is not unnecessary

**Pull request merged**
