### PR TITLE
Run container tests in gophercloud

### PR DESCRIPTION
**Pull request by hongbin**

### CODE REVIEW

**Comment by hongbin** [comment]
FYI @kevin-zhaoshuai @jtopjian

**Comment by mrhillsman** [comment]
Approved

**Comment by mrhillsman** [comment]
@hongbin maybe a rebase is needed?

**Comment by hongbin** [comment]
@mrhillsman done

**Comment by hongbin** [comment]
@kevin-zhaoshuai , after this patch, the Gophercloud CI complained with the following error:

2018-05-03 20:54:35.466505 | ubuntu-xenial | === RUN   TestCapsuleGet
2018-05-03 20:54:37.478933 | ubuntu-xenial | --- FAIL: TestCapsuleGet (2.01s)
2018-05-03 20:54:37.479158 | ubuntu-xenial | 	convenience.go:35: [1;31mFailure in capsules_test.go, line 24: unexpected error [0m[1;33m"Resource not found"[0m[1;31m[0m

Here is the log: http://logs.openlabtesting.org/logs/27/927/70f04e44e91c14b867c5ead4b8e859b57864213e/check/gophercloud-acceptance-test/c6401f7/job-output.txt.gz

See if you can quickly fix it. If not, we need to propose a revert to restore the CI.

**Comment by jtopjian** [comment]
Also, just to quickly note: the `TestCapsuleCreate` test is passing (🎉), so it's definitely an issue with the test itself. This is good news since we can easily clean this up.

@kevin-zhaoshuai Since this is related to capsules, you can reference issue #700 when submitting a PR. Ping me when it's ready and I'll merge it 😄

**Comment by kevin-zhaoshuai** [comment]
@jtopjian @hongbin Yes the issue is based on the hard code uuid. I will get capsule List rebase and ready first and use List operation instead of hard code UUID.

**Comment by kevin-zhaoshuai** [comment]
@jtopjian @hongbin https://github.com/gophercloud/gophercloud/pull/955  This PR can fix this issue.

**Comment by jtopjian** [comment]
Merged :)

**Pull request merged**
