### PR TITLE
pipelines: add support for newer OpenStack releases

### PR DESCRIPTION
**Pull request by EmilienM**
Add new pipelines for the recent versions of OpenStack:

* Victoria
* Wallaby
* Xena

Issue #2253

### CODE REVIEW

**Comment by EmilienM** [comment]
cc @lingxiankong

**Comment by EmilienM** [comment]
recheck

**Comment by EmilienM** [comment]
@wangxiyuan when CI is green please have a look.

**Comment by wangxiyuan** [comment]
@ffrog this change need a zuul restart once merged. Please take a look. Thanks.

**Review by wangxiyuan — APPROVED** [review]

**Pull request merged**
