### PR TITLE
Add support for running packer-1.2.5 with public clouds

### PR DESCRIPTION
**Pull request by liu-sheng**

### CODE REVIEW

**Comment by kiwik** [comment]
Add project `theopenlab/packer` into zuul main.yaml and restart zuul, this failing will gone.

**Comment by liu-sheng** [comment]
recheck

**Comment by liu-sheng** [comment]
recheck

**Comment by liu-sheng** [comment]
looks like a bug  about one-line statement "include_role: name=xxx"  of ansible-lint

**Pull request merged**
