### PR TITLE
Bump etcd version for OpenStack k8s cloud provider

### PR DESCRIPTION
**Pull request by kayrus**
/cc @adisky 
relates to https://github.com/kubernetes/cloud-provider-openstack/pull/762

### CODE REVIEW

**Comment by adisky** [comment]
@kayrus Thanks for the update!!
/lgtm

**Comment by adisky** [comment]
@wangxiyuan @huangtianhua could we merge this?

**Comment by kayrus** [comment]
@wangxiyuan how fast the changes are proposed to the live openlab?

**Comment by wangxiyuan** [comment]
@kayrus basiclly, if you change the files in `zuul.d` folder, it needs a zuul restart to adopt the change.
Otherwise, the change will be adopted at once.

So for this change, once it's merged, it'll be actived at once.

Any problem you hit?

**Pull request merged**
